#!/bin/bash
#
# tsükkel

	echo -n "Sisesta ridade arv: "
read ridadearv
	echo -n "Sisesta tärnide arv: "
read tarnid 

for (( i = 1 ; i <= $ridadearv ; i++ ))
do
	echo -n "$i. "
	if [ $i -eq 1 -o $i -eq $ridadearv ]; then
		for (( j = 1 ; j<= $tarnid; j++ ))
		do
			echo -n "*"
		done
	else
	tyhik=$(($tarnid - 2))
			echo -n "*"
		for (( n = 1 ; n <= $tyhik ; n++ ))
		do
			echo -n " "
		done
			echo -n "*"
	fi
	echo ""
done
