#!/bin/bash
#
#10 numbri tagurpidi lugemine ja paarisarvude liitmine
summa=0
for (( i=10; i>1; i-- ))
do
	echo $i
		jaak=$(($i%2))
	if [ $jaak -eq 0 ]; then
		summa=$(($summa+$i))
	fi
done
	echo "Paarisarvude summa on $summa"
