#!/bin/bash
#
# tsükliga kujundid: Kolmnurk vasakult paremale.
echo "Sisesta ridade arv: "
read rida
for (( i = 1; i <= $rida; i++ ))
do
	for (( j = 1 ; j <= i ; j++ ))
	do
		echo -n "*"
	done
echo ""
done
