#!/bin/bash
#
# tsükliga kujundid: Kolmnurk paremalt vasakule.
echo -n "Sisesta ridade arv: "
read rida
for ((r=1; r<$rida+1; r++))
do
echo -n "$r "
	for (( v=1; v<$(($rida+1-$r+1)); v++))
	do
		echo -n "*"
done
echo ""
done
