#!/bin/bash
#
# muutuja kasutamise näide
#
kasutaja=`whoami`
kell=`date +"%H:%M"`
kuupaev=`date +"%d. %B"`

echo "Tere $kasutaja" #väljastan vastava muutuja väärtuse koos seletusega
echo "Kell on $kell" #väljastan muutuja kellaaja
echo "Täna on $kuupaev" #väljastan muutuja kuupäeva
