#!/bin/bash
#
	echo -n "Sisesta arv: "
read arv
if [ $arv -gt 0 ]; then		#kui arv > 0 siis echo
	echo "$arv on positiivne."
elif [ $arv -lt 0 ]; then	#muidu kui arv < 0 siis echo
	echo "$arv on negatiivne."
else
	echo "$arv on neutraalne."
fi

