#!/bin/bash
# Pingimine kasutaja poolt sisestatud IP vahemikus.
pun=`tput setaf 1`	#punane värv
roh=`tput setaf 2`	#roheline värv
reset=`tput sgr0`	#taastab algvärvi juurde

kp=$(date +"%H.%M-%d.%m.%Y")

echo "Syntax: ${roh} 172.23.13 $reset"
echo -n "Sisesta IP algus: "
read IP1

echo "Syntax: ${roh} 30 $reset"
echo -n "Sisesta IP vahemiku algus: "
read algus					#küsi vahemiku algust

echo "Syntax: ${roh} 35 $reset"
echo -n "Sisesta IP vahemiku lõpp: "
read lopp					#küsi vahemiku lõppu

for ((tee=$algus; tee<=$lopp; tee++))
do
	ip="$IP1.$tee"
	mkdir -p ./ping-logs/$IP1/$algus-$lopp
	ping -c 2 $ip > /dev/null

		if [ $? -eq 0 ]; then
			echo " ${roh}$ip - OK" >> "./ping-logs/$IP1/$algus-$lopp/$kp.log"
			echo " ${roh}$ip - OK"
			echo "$reset" >> "./ping-logs/$IP1/$algus-$lopp/$kp.log"

		else
			echo " ${pun}$ip - NOT OK" >> "./ping-logs/$IP1/$algus-$lopp/$kp.log"
			echo " ${pun}$ip - NOT OK"
			echo "$reset" >> "./ping-logs/$IP1/$algus-$lopp/$kp.log"
		fi
done
echo "${roh} Logid on salvestatud järgmises kaustas: ./ping-logs/IP/IP range/time-date.log"
tput sgr0
